/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/2/auth/simple-token/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Obtain a simple (read) API token
     * @description Exchange `username` and `password` for a long-lived `token`. Use `Authorization: Token <token>` on API v2.
     *     Official tutorial uses `POST https://exist.io/api/2/auth/simple-token/`. Older copy on the important-values page referenced `/api/1/`; prefer v2.
     */
    post: operations["authSimpleToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth2/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * OAuth2 authorization (user browser step)
     * @description Redirect end user here. On success Exist redirects to `redirect_uri` with `?code=...`.
     *     `redirect_uri` must be HTTPS in production (see official OAuth2 reference).
     */
    get: operations["oauth2Authorize"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth2/access_token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange authorization code or refresh token */
    post: operations["oauth2AccessToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/accounts/profile/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Current user profile
     * @description Recommended check that a token works.
     */
    get: operations["getAccountsProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/attributes/with-values/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List attributes with values (paged)
     * @description Typical query params include `page`, `limit`, `days`, `groups`, `date_max`, `attributes`
     *     (filter to specific attribute names). Default pagination ~20 items per page.
     */
    get: operations["getAttributesWithValues"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/averages/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List attribute averages / goals (paged)
     * @description Query params include `attributes` (filter), `include_historical` (truthy for history),
     *     `page`, `limit` per official read-client guide.
     */
    get: operations["getAverages"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/correlations/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List correlations (paged) */
    get: operations["getCorrelations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/correlations/combo/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Single correlation for an attribute pair */
    get: operations["getCorrelationCombo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/attributes/acquire/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Acquire ownership of attributes (write clients)
     * @description JSON array of objects with `template` or `name`, and `manual` boolean.
     *     Requires Bearer token with appropriate write scope.
     */
    post: operations["postAttributesAcquire"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/attributes/release/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Release ownership of attributes */
    post: operations["postAttributesRelease"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/attributes/create/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create custom attributes
     * @description Array of objects with `label`, `value_type` (integer enum), `group`, `manual`.
     */
    post: operations["postAttributesCreate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/attributes/update/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Set attribute totals for one or more dates
     * @description Array of `{ "name", "date" (yyyy-mm-dd), "value" }` objects.
     */
    post: operations["postAttributesUpdate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/2/attributes/increment/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Increment attribute values (often for "today")
     * @description Array of `{ "name", "value" }`; optional `date` omitted defaults to today per tutorial.
     */
    post: operations["postAttributesIncrement"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
// Re-export commonly used types for convenience
export type UserProfile = components["schemas"]["UserProfile"];
export type AttributeWithValues = components["schemas"]["AttributeWithValues"];
export type PagedAttributesWithValues = components["schemas"]["PagedAttributesWithValues"];

export interface components {
  schemas: {
    SimpleTokenResponse: {
      token?: string;
    };
    OAuthAuthorizationCodeRequest: {
      /** @enum {string} */
      grant_type: "authorization_code";
      code: string;
      client_id: string;
      client_secret: string;
      /** Format: uri */
      redirect_uri: string;
    };
    OAuthRefreshTokenRequest: {
      /** @enum {string} */
      grant_type: "refresh_token";
      refresh_token: string;
      client_id: string;
      client_secret: string;
    };
    OAuthAccessTokenResponse: {
      access_token?: string;
      /** @example Bearer */
      token_type?: string;
      /** @description Seconds until access token expiry (docs cite ~1 year). */
      expires_in?: number;
      refresh_token?: string;
      /** @description Space-separated granted scopes */
      scope?: string;
    };
    /** @description Profile object (subset; see object types reference). */
    UserProfile: {
      username?: string;
      first_name?: string;
      last_name?: string;
      /** Format: uri */
      avatar?: string;
      timezone?: string;
      /** Format: date-time */
      local_time?: string;
      imperial_distance?: boolean;
      imperial_weight?: boolean;
      imperial_energy?: boolean;
      imperial_liquid?: boolean;
      imperial_temperature?: boolean;
      trial?: boolean;
      delinquent?: boolean;
    } & {
      [key: string]: unknown;
    };
    AttributeGroup: {
      name?: string;
      label?: string;
      priority?: number;
    };
    AttributeService: {
      name?: string;
      label?: string;
    };
    AttributeValueDay: {
      /** Format: date */
      date?: string;
      value?: unknown;
    };
    AttributeWithValues: {
      group?: components["schemas"]["AttributeGroup"];
      template?: string | null;
      name?: string;
      label?: string;
      priority?: number;
      manual?: boolean;
      active?: boolean;
      value_type?: number;
      value_type_description?: string;
      service?: components["schemas"]["AttributeService"];
      values?: components["schemas"]["AttributeValueDay"][];
    } & {
      [key: string]: unknown;
    };
    PagedAttributesWithValues: {
      count?: number;
      /** Format: uri */
      next?: string | null;
      /** Format: uri */
      previous?: string | null;
      results?: components["schemas"]["AttributeWithValues"][];
    };
    AverageRow: {
      user_attribute?: string;
      /** Format: date */
      date?: string;
      overall?: number;
      monday?: number;
      tuesday?: number;
      wednesday?: number;
      thursday?: number;
      friday?: number;
      saturday?: number;
      sunday?: number;
    } & {
      [key: string]: unknown;
    };
    PagedAverages: {
      count?: number;
      next?: string | null;
      previous?: string | null;
      results?: components["schemas"]["AverageRow"][];
    };
    Correlation: {
      /** Format: date */
      date?: string;
      period?: number;
      offset?: number;
      attribute?: string;
      attribute2?: string;
      value?: number;
      p?: number;
      percentage?: number;
      stars?: number;
      second_person?: string;
      second_person_elements?: string[];
      attribute_category?: unknown;
      strength_description?: string;
      stars_description?: string;
      description?: unknown;
      occurrence?: unknown;
      rating?: unknown;
    } & {
      [key: string]: unknown;
    };
    PagedCorrelations: {
      count?: number;
      /** Format: uri */
      next?: string | null;
      previous?: string | null;
      results?: components["schemas"]["Correlation"][];
    };
    /** @description Use `template` OR `name` per acquire rules in write-client guide. */
    AcquireOrReleaseItem: {
      template?: string;
      name?: string;
      manual?: boolean;
    };
    CreateAttributeItem: {
      label: string;
      /**
       * @description 0 quantity, 1 decimal, 2 string, 3 duration minutes, 4 time from midnight,
       *     5 percentage, 7 boolean, 8 scale — see object types reference (6 reserved).
       */
      value_type: number;
      group: string;
      manual: boolean;
    };
    AttributeValueUpdate: {
      name: string;
      /** Format: date */
      date: string;
      value: unknown;
    };
    AttributeIncrement: {
      name: string;
      value: unknown;
      /**
       * Format: date
       * @description Optional; defaults to today when omitted.
       */
      date?: string;
    };
  };
  responses: {
    /** @description Invalid or expired token */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    /** @description Rate limited (300 requests per hour per user token) */
    TooManyRequests: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
  };
  parameters: {
    Page: number;
    /** @description Page size (tutorial used up to 100). */
    Limit: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  authSimpleToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": {
          username: string;
          password: string;
        };
        "application/json": {
          username: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description Token issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SimpleTokenResponse"];
        };
      };
      429: components["responses"]["TooManyRequests"];
    };
  };
  oauth2Authorize: {
    parameters: {
      query: {
        response_type: "code";
        client_id: string;
        redirect_uri: string;
        /** @description Space-separated scopes (e.g. `media_write mood_read`). */
        scope: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to Exist login or to client redirect_uri with code or error */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  oauth2AccessToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded":
          | components["schemas"]["OAuthAuthorizationCodeRequest"]
          | components["schemas"]["OAuthRefreshTokenRequest"];
      };
    };
    responses: {
      /** @description Token response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OAuthAccessTokenResponse"];
        };
      };
    };
  };
  getAccountsProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserProfile"];
        };
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  getAttributesWithValues: {
    parameters: {
      query?: {
        page?: components["parameters"]["Page"];
        /** @description Page size (tutorial used up to 100). */
        limit?: components["parameters"]["Limit"];
        /** @description Number of days of values ending at most recent (e.g. `7`). */
        days?: number;
        /** @description Filter by group name (e.g. `custom` for tags). */
        groups?: string;
        /** @description YYYY-MM-DD; values align to this date window per docs. */
        date_max?: string;
        /** @description Comma-separated or repeated attribute `name` filters (per tutorial usage). */
        attributes?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paged attributes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedAttributesWithValues"];
        };
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  getAverages: {
    parameters: {
      query?: {
        page?: components["parameters"]["Page"];
        /** @description Page size (tutorial used up to 100). */
        limit?: components["parameters"]["Limit"];
        attributes?: string;
        include_historical?: 0 | 1;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paged averages */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedAverages"];
        };
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  getCorrelations: {
    parameters: {
      query?: {
        page?: components["parameters"]["Page"];
        /** @description Page size (tutorial used up to 100). */
        limit?: components["parameters"]["Limit"];
        /** @description When `1`, filter to statistically confident correlations. */
        confident?: 0 | 1;
        /** @description Filter correlations involving this attribute name. */
        attribute?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paged correlations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedCorrelations"];
        };
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  getCorrelationCombo: {
    parameters: {
      query: {
        attribute: string;
        attribute2: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One correlation object */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Correlation"];
        };
      };
      401: components["responses"]["Unauthorized"];
      /** @description No correlation for that pair */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      429: components["responses"]["TooManyRequests"];
    };
  };
  postAttributesAcquire: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcquireOrReleaseItem"][];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  postAttributesRelease: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcquireOrReleaseItem"][];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  postAttributesCreate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAttributeItem"][];
      };
    };
    responses: {
      /** @description Created; body includes `success` array per tutorial */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  postAttributesUpdate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttributeValueUpdate"][];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  postAttributesIncrement: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttributeIncrement"][];
      };
    };
    responses: {
      /** @description Success; tutorial shows `success[0].current` for new total */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
}
